server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off  # 关闭mybatisplus启动图标
    db-config:
      id-type: auto

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 配置管理端
    admin-secret-key: admin_secret_key  # 设置jwt签名加密时使用的秘钥
    admin-ttl: 604800000  # 设置jwt过期时间,单位ms，时间一周
    admin-token-name: token  # 设置前端传递过来的令牌名称

    # 配置为微信用户生成jwt令牌时使用的配置项
    user-secret-key: user_secret_key
    user-ttl: 604800000
    user-token-name: authentication

  # 配置微信支付
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}

    mchid : ${sky.wechat.mchid}
    mchSerialNo: ${sky.wechat.mchSerialNo}
    privateKeyFilePath: ${sky.wechat.privateKeyFilePath}
    apiV3Key: ${sky.wechat.apiV3Key}
    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
    notifyUrl: ${sky.wechat.notifyUrl}
    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}
  # 配置存储服务器
  minio:
    endpoint: ${sky.minio.endpoint}
    bucketName: ${sky.minio.bucketName}
    accessKey: ${sky.minio.accessKey}
    secretKey: ${sky.minio.secretKey}
  # 配置百度地图
  baidu:
    ak: ${sky.baidu.ak}
    shopAddress: ${sky.baidu.shopAddress}
    coordinateUrl: ${sky.baidu.coordinateUrl}
    distanceUrl: ${sky.baidu.distanceUrl}

